name: Debug

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "README.md"
      - "CHANGELOG.md"
    branches:
      - master

env: 
  TZ: Asia/Shanghai

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
          echo "commit_hash=$(git rev-parse HEAD | cut -c 1-7 )" >> "$GITHUB_OUTPUT"
          version=$(sed -n 's/^version=\(v[0-9.]*\)$/\1/p' module.prop)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ steps.get_version.outputs.version }}_debug/g" module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" module.prop
      
      - name: Generate Asset
        run: |
          sudo mkdir -p /box_for_magisk
          sudo cp -r --parents $(find ./ -type f ! -path './.git/*' ! -name 'CHANGELOG.md' ! -name 'update.json' ! -name 'build.sh' ! -path './.github/*' ! -path './docs/*')  /box_for_magisk/
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "box_for_magisk_${{ steps.get_version.outputs.version }}_${{ steps.get_version.outputs.commit_hash }}_${{ steps.get_version.outputs.date }}"
          path: /box_for_magisk/