name: Release

on:
  workflow_dispatch:

env: 
  TZ: Asia/Shanghai

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
          echo "commit_hash=$(git rev-parse HEAD | cut -c 1-7 )" >> "$GITHUB_OUTPUT"
          version=$(sed -n 's/^version=\(v[0-9.]*\)$/\1/p' module.prop)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update update.json and module.prop
        run: |
          echo '{
            "version": "${{ steps.get_version.outputs.version }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "https://github.com/d2184/box_for_magisk/releases/download/${{ steps.get_version.outputs.version }}/box_for_magisk-${{ steps.get_version.outputs.version }}.zip",
            "changelog": "https://github.com/d2184/box_for_magisk/raw/master/CHANGELOG.md"
          }' > update.json

          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ steps.get_version.outputs.version }}/g" module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" module.prop

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add update.json module.prop
          git commit --message="${{ steps.get_version.outputs.version }}"
          git push origin master -f

      - name: run build.sh
        run: |
          sh build.sh

      - name: Create GitHub Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          file: box_for_magisk-v*.zip
          prerelease: false
          overwrite: true
          file_glob: true